### ISSUE TITLE
Design Docs Review

### ISSUE THREAD

**Issue by vawhitehouse** [ArtemSilka/Puntiresse#1]
## MVP
- User Auth: 
  - [x]  Typo: "sing" -> "sign" (four places)
- Boards and Pins: 
  - [x]  Users should be able to view a list(index) of pins
- You might want to consider reordering your MVPs. I would recommend doing Boards/Pins and the discovery feed before the user profile. This is mainly because the discovery feed (which is basically a pin index) is the first thing you see when you log in.

## Schema
- `users`:
  - [x] `session_token` should be indexed
- `board_pins` and `follows`:
  - [x] all foreign key should be indexed

## Sample State
- `entities.users`:
  - [x] you will probably want to keep track of a user's pins and boards (eg, `createdPins: [2,5,6]`)
  - [x] same for keeping track of followers/followed users
- `entities.boards`:
  - [x] should keep track of pins on the board 
- `entities.follows`
  - I don't think you'll need this. You can keep this as an array of ids within the `users` slice of state.

Backend and frontend routes look good!

**Comment by ArtemSilka** [comment]
Hi, Valerie!

Thank you for prompt review. 
I've corrected all above.
Quick question, if I would like to have `Profile image`,  I'll need to add row to `Users` table right? But do I need to reflect this in the state? Or it depends?

Thank you again.

**Comment by vawhitehouse** [comment]
You won't need to store the image info within your database - we will use AWS (Amazon Web Services) for images.
