### ISSUE TITLE
User Auth completion 

### ISSUE THREAD

**Issue by ArtemSilka** [ArtemSilka/Puntiresse#2]
Hi Valerie, 

I've completed following mvps

- [ ] 1. Hosting on Heroku(Jul 27th)

- [ ] 2. Create account, sign in, demo login(Jul 28th, 2 days)

> - [ ] New users can create an account

> - [ ] Existing users can sign in/ sign out

> - [ ] Demo login available to discover application

> - [ ] All users must sign in to use most features

**Comment by vawhitehouse** [comment]
Overall it looks really nice! Here are few things to look at:

- [ ] Remove anything that is non-functional (Facebook login, Google login, Terms of service, Privacy Policy, etc.)
- [ ] The `X` to close the modal is hard to see - it looks like Pinterest uses a white or light gray `X` 
- [ ] Input fields should be outlined in red if there is an error being displayed.

**Comment by ArtemSilka** [comment]
Hi, Valerie. 
Thank you for review! I've addressed all above.
Also decided to change `x` close the modal to different icon and made background-color the same as modal-box color. Pic attached. 
 
<img width="992" alt="Screen Shot 2020-07-31 at 11 13 45 PM" src="https://user-images.githubusercontent.com/64483987/89092877-842dec00-d383-11ea-9769-47c06a4bc199.png">

**Comment by ArtemSilka** [comment]
Let me know if that's ok or anything else needed. Thank you
